{{- if and .Values.certManager.enabled .Values.certManager.externalSecret -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.certManager.externalSecret.name }}
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp
  target:
    name: {{ .Values.certManager.externalSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: {{ .Values.certManager.externalSecret.onePasswordSecretName }}
{{ end }}
