---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: sonarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: sonarr-data-nfs
