apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-nvmeof-nvme-config
  namespace: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: democratic-csi-nvmeof-nvme-config
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |-
          driver: zfs-generic-nvmeof
          sshConnection:
            host: {{ .truenas_host }}
            port: 22
            username: {{ .truenas_user }}
            privateKey: |-{{ .truenas_ssh_key | b64dec | nindent 4}}
          zfs:
            cli:
              sudoEnabled: true
              paths:
                zfs: /sbin/zfs
                zpool: /sbin/zpool
                sudo: /bin/sudo
                chroot: /sbin/chroot
            datasetParentName: nvme/k8s/vols
            detachedSnapshotsDatasetParentName: nvme/k8sbak/vols
            zvolCompression: lz4
            zvolDedup: false
            zvolEnableReservation: false
            zvolBlocksize: 16k
          nvmeof:
            transports:
              - "tcp://{{ .truenas_host }}:4420?ctrl-loss-tmo=30"
            namePrefix: ""
            nameSuffix: ""
            shareStrategy: nvmetCli
            shareStrategyNvmetCli:
              sudoEnabled: true
              nvmetcliPath: /root/.local/bin/nvmetcli
              configPath: /mnt/nvme/k8s/nvmet-config.json
              configIsImportedFilePath: /run/nvmet-config-loaded
              basename: nqn.2003-01.org.linux-nvmeof.ubuntu-19.x8664
              ports:
                - "1"
              subsystem:
                attributes:
                  allow_any_host: 1
  dataFrom:
  - extract:
      key: truenas
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None