apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-env
  namespace: hermes-assistant
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-agents
  target:
    name: hermes-env
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: API_SERVER_KEY
      remoteRef:
        key: hermes-assistant
        property: api_server_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_USERNAME
      remoteRef:
        key: hermes-assistant
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH
      remoteRef:
        key: hermes-assistant
        property: password_hash
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: HERMES_DASHBOARD_BASIC_AUTH_SECRET
      remoteRef:
        key: hermes-assistant
        property: password_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: hermes
        property: slack_app_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: hermes
        property: slack_bot_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OPENCODE_GO_API_KEY
      remoteRef:
        key: opencode-go-api-key
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
