apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
  namespace: test-tekton-pipeline
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World"