apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipeline-helloworld
resources:
- goodbye-task.yml
- hello-goodbye-pipeline.yml
- hello-task.yml
- tekton-pipeline-helloworld-namespace.yml
- hello-binding-triggerbinding.yml
- hello-template-triggertemplate.yml
- hello-listener-eventlistener.yml
- el-hello-listener-route.yml