apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp-pull
  target:
    name: dns-token
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - extract:
      key: dns-token
