---
apiVersion: v1
kind: Endpoints
metadata:
  # Must match the Service name for endpoint discovery.
  name: truenas-ipmi
  labels:
    app.kubernetes.io/name: truenas-ipmi
    app.kubernetes.io/part-of: truenas
subsets:
  - addresses:
      - ip: 10.10.9.243
    ports:
      - name: metrics
        port: 9290
        protocol: TCP
