apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: dummy-net
  namespace: multus-dummy-device
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "dummy-net",
      "type": "dummy",
      "ipam": {
        "type": "host-local",
        "subnet": "10.1.1.0/24"
      }
    }
