apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-dummy-device
resources:
  - multus-dummy-device-namespace.yaml
  - dummy-net-networkattachmentdefinition.yaml
  - multus-dummy-device-test-pod.yaml
