---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-monitoring-config-configmap.yaml
  - user-workload-monitoring-config-configmap.yaml
  - exporters/adb-exporter
  - exporters/blackbox-exporter
  - exporters/mktxp
  - exporters/mx3d
  - exporters/olm-state-metrics
  - exporters/upsmonitor
  - exporters/vscode
  - exporters/truenas
  - exporters/rk8s-federate
  - exporters/snmp-exporter
  - rules/externalsecrets-alerts-prometheusrule.yaml
  - rules/cert-manager-alerts-prometheusrule.yaml
  - rules/cnpg-alerts-forgejo-prometheusrule.yaml
  - rules/cnpg-alerts-keycloak-prometheusrule.yaml
  - rules/cnpg-alerts-rhdh-prometheusrule.yaml
  - rules/cnpg-alerts-quay-enterprise-prometheusrule.yaml
  - servicemonitors/argocd-servicemonitor.yaml
  - servicemonitors/cert-manager-servicemonitor.yaml
  - servicemonitors/external-secrets-podmonitor.yaml
  - servicemonitors/grafana-operator-servicemonitor.yaml
