---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: '5'
    argocd.argoproj.io/sync-options: ServerSideApply=true
data:
  config.yaml: |
    prometheus:
      logLevel: info
      retention: 15d
      volumeClaimTemplate:
        spec:
          storageClassName: freenas-nvmeof-fast-csi
          resources:
            requests:
              storage: 20Gi
    thanosRuler:
      logLevel: info
      retention: 15d
      volumeClaimTemplate:
        spec:
          storageClassName: freenas-nvmeof-fast-csi
          resources:
            requests:
              storage: 10Gi
    alertmanager:
      enabled: true
      enableAlertmanagerConfig: true
