apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-config
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/ocp-base-config
    repoURL: https://github.com/igou-io/igou-openshift.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
