---
global:
  gc: false
  gcMetrics: true
  deletionStrategy: default
  measurements:
   - name: jobLatency
   - name: pvcLatency
metricsEndpoints:
  - indexer:
      type: local
jobs:
  - name: nfs-fast
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nfs-fast-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: nfs-ssd
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nfs-ssd-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: nfs-cold
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nfs-cold-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: nvmeof-fast
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-fast-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: nvmeof-ssd
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-ssd-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: nvmeof-cold
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-cold-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: iscsi-fast
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-iscsi-fast-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: iscsi-ssd
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-iscsi-ssd-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: iscsi-cold
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-iscsi-cold-csi
          storageSize: 30Gi
          containerImage: fedora

  - name: lvms-vg1-worker
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: yabs-fio
    waitWhenFinished: true
    podWait: true
    objects:
      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: lvms-vg1-worker
          storageSize: 30Gi
          containerImage: fedora
