---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-networkpolicy.yaml
  - allow-observed-networkpolicy.yaml
  - rhacs-operator-namespace.yaml
  - stackrox-namespace.yaml
  - rhacs-operator-group-operatorgroup.yaml
  - rhacs-operator-subscription.yaml
  - sensor-tls-externalsecret.yaml
  - collector-tls-externalsecret.yaml
  - admission-control-tls-externalsecret.yaml
  - central-declarative-config-configmap.yaml
  - stackrox-central-services-central.yaml
  - stackrox-secured-cluster-services-securedcluster.yaml
  - cluster-apps-privileged-container-securitypolicy.yaml
  - cluster-apps-sensitive-host-mounts-securitypolicy.yaml
  - cluster-apps-runtime-socket-mount-securitypolicy.yaml
  - cluster-apps-cap-sys-admin-securitypolicy.yaml
  - cluster-apps-secret-in-env-securitypolicy.yaml
