apiVersion: v2
name: ocp-base-config
description: Base cluster configurations via Helm

type: application

version: 0.0.1

appVersion: "4.15"
dependencies:
  - name: connect
    repository: https://1password.github.io/connect-helm-charts
    version: 1.15.0
