cluster:
  name: sno
  baseDomain: igou.systems
  gitOpsRepo: https://github.com/igou-io/igou-openshift.git
  gitOpsBasePath: config
  trustedCABundle: ""
  openshiftVersion: "4.15"

externalSecrets:
  enabled: true
  vaults:
    openshift: 1


certManager:
  enabled: true
  apiCert: true
  defaultIngressCert: true
  acmeBase: 'https://acme-v02.api.letsencrypt.org/directory'
  externalSecret:
    name: dns-token
    onePasswordSecretName: dns-token
  solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: credential
            name: dns-token
          email: igou.david@gmail.com
      selector:
        dnsZones:
          - igou.systems


monitoring:
  enabled: false
  storageClass: standard

network:
  hostRouting: false

auth:
  enabled: false
  oidcDisplayName: igou
  oidcClientID: openshift
  oidcIssuer: ''
  externalSecret:
    name: oauth-signal9-client-secret
    vaultName: signal9-openid

timesync:
  enabled: false
  ptp:
    enabled: false
    loadKvmModule: false
    device: 'ptp_kvm'
    sourceStratum: 2
  ntpServers:
    - 1.2.3.4

gitops:
  applicationControllerResources: {}
  kustomizeBuildOptions: "--enable-helm"