apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-system-namespace.yaml
  - metallb-operator-operatorgroup.yaml
  - metallb-operator-subscription.yaml
  - metallb-metallb.yaml
