---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  name: centos-stream10-casval
  namespace: openshift-virtualization-os-images
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    molecule.igou.systems/image-cache: casval
spec:
  schedule: '13 * * * *'
  managedDataSource: centos-stream10-casval
  importsToKeep: 1
  garbageCollect: Outdated
  retentionPolicy: None
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      source:
        registry:
          pullMethod: node
          url: docker://quay.io/containerdisks/centos-stream:10
      storage:
        storageClassName: lvms-casval
        accessModes:
          - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: 30Gi
