---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - molecule-namespace.yaml
  - centos-stream10-casval-dataimportcron.yaml
  - win11-casval-dataimportcron.yaml
  - win2k25-casval-dataimportcron.yaml
