---
global:
  gc: false
  gcMetrics: true
  deletionStrategy: default
  measurements:
   - name: jobLatency
   - name: pvcLatency
metricsEndpoints:
  - indexer:
      type: local
jobs:
  - name: pod-job-pvc
    jobIterations: 1
    qps: 300
    burst: 300
    preLoadImages: false
    namespacedIterations: false
    namespace: pod-job-pvc
    waitWhenFinished: true
    podWait: true
    objects:

      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nfs-fast-csi
          storageSize: 30Gi
          containerImage: fedora

      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nfs-ssd-csi
          storageSize: 30Gi
          containerImage: fedora

      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nfs-cold-csi
          storageSize: 30Gi
          containerImage: fedora

      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-fast-csi
          storageSize: 30Gi
          containerImage: fedora

      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-ssd-csi
          storageSize: 30Gi
          containerImage: fedora

      - objectTemplate: templates/bundle.yml
        replicas: 1
        inputVars:
          storageClassName: freenas-nvmeof-cold-csi
          storageSize: 30Gi
          containerImage: fedora