{{- if and .Values.auth.enabled .Values.auth.openID.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.auth.openID.externalSecret.name }}
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-openshift
  target:
    name: {{ .Values.auth.openID.externalSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        clientSecret: {{ "{{ .client_secret }}" | quote }}
  dataFrom:
    - extract:
        key: {{ .Values.auth.openID.externalSecret.onePasswordSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
