---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-qbittorrent
  namespace: shelfmark
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-openshift
  target:
    name: shelfmark-qbittorrent
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        QBITTORRENT_PASSWORD: "{{ .password }}"
        QBITTORRENT_USERNAME: "{{ .username }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: shelfmark-qbittorrent
        metadataPolicy: None
        nullBytePolicy: Ignore
