---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shelfmark-prowlarr
  namespace: shelfmark
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-openshift
  target:
    name: shelfmark-prowlarr
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        PROWLARR_API_KEY: "{{ .password }}"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: shelfmark-prowlarr
        metadataPolicy: None
        nullBytePolicy: Ignore
