---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-books
  namespace: shelfmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: shelfmark-static-nfs
  volumeName: shelfmark-books-nfs
