apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  encryption:
    type: identity
  servingCerts:
    namedCertificates:
    - names:
      - api.hub.igou.systems
      servingCertificate:
        name: acme-api
