apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: lvmcluster
  namespace: openshift-storage
spec:
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  storage:
    deviceClasses:
    - name: lvm-local-storage
      deviceSelector:
        forceWipeDevicesAndDestroyAllData: true
        paths:
        - /dev/nvme0n1p5
      fstype: xfs
      thinPoolConfig:
        chunkSizeCalculationPolicy: Static
        metadataSizeCalculationPolicy: Host
        name: lvm-local-storage-thin-pool
        overprovisionRatio: 10
        sizePercent: 90