apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: lvms-lvm-local-storage-immediate
provisioner: topolvm.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
