apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-omnigent-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-agents
  target:
    name: keycloak-omnigent-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        OMNIGENT_OPENSHELL_CLIENT_SECRET: '{{ .OPENSHELL_CLIENT_SECRET }}'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: omnigent-openshell
        metadataPolicy: None
        nullBytePolicy: Ignore
