---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-networkpolicy.yaml
  - allow-required-networkpolicy.yaml
  - keycloak-namespace.yaml
  - rhbk-operatorgroup.yaml
  - rhbk-operator-subscription.yaml
  - keycloak-pg-credentials-externalsecret.yaml
  - keycloak-realm-secrets-externalsecret.yaml
  - cnpg-s3-credentials-externalsecret.yaml
  - keycloak-pg-backup-objectstore.yaml
  - keycloak-pg-cluster.yaml
  - keycloak-pg-daily-scheduledbackup.yaml
  - keycloak-tls-certificate.yaml
  - keycloak-keycloak.yaml
  - igou-keycloakrealmimport.yaml
