apiVersion: v1
kind: Pod
metadata:
  name: mc-backup-idle
  namespace: minecraft-server
  labels:
    app: mc-backup-idle
spec:
  restartPolicy: Always
  containers:
    - name: mc-backup
      image: itzg/mc-backup:latest@sha256:3fec3f8566eab04dd78e74b1f10236cb622458301dbc04ead4c81a679d352650
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: minecraft-datadir
          mountPath: /data
  volumes:
    - name: minecraft-datadir
      persistentVolumeClaim:
        claimName: minecraft-datadir
