apiVersion: v1
kind: Pod
metadata:
  name: mc-backup-idle
  namespace: minecraft-server
  labels:
    app: mc-backup-idle
spec:
  restartPolicy: Always
  containers:
    - name: mc-backup
      image: itzg/mc-backup:latest@sha256:11d38fb3f08e677f98d1d95c032a50c37a1737c2893564fc12492abae082555e
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: minecraft-datadir
          mountPath: /data
  volumes:
    - name: minecraft-datadir
      persistentVolumeClaim:
        claimName: minecraft-datadir
