apiVersion: v1
kind: Pod
metadata:
  name: mc-backup-idle
  namespace: minecraft-server
  labels:
    app: mc-backup-idle
spec:
  restartPolicy: Always
  containers:
    - name: mc-backup
      image: itzg/mc-backup:latest@sha256:bdfe8e90c70e8901e696464c436aace2c111d61300309e65c4cff1e86d3f1ed4
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: minecraft-datadir
          mountPath: /data
  volumes:
    - name: minecraft-datadir
      persistentVolumeClaim:
        claimName: minecraft-datadir
