apiVersion: v1
kind: Pod
metadata:
  name: mc-backup-idle
  namespace: minecraft-server
  labels:
    app: mc-backup-idle
spec:
  restartPolicy: Always
  containers:
    - name: mc-backup
      image: itzg/mc-backup:latest@sha256:77e62a6f3af5a2e3ec2fabaa542f3b970f62795e5993a1805520b6cee77d0a36
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: minecraft-datadir
          mountPath: /data
  volumes:
    - name: minecraft-datadir
      persistentVolumeClaim:
        claimName: minecraft-datadir
