apiVersion: v1
kind: Pod
metadata:
  name: mc-backup-idle
  namespace: minecraft-server
  labels:
    app: mc-backup-idle
spec:
  restartPolicy: Always
  containers:
    - name: mc-backup
      image: itzg/mc-backup:latest@sha256:4fd91f83965d2fc38f846bd35e1201baef44ecc77a281b2c05bb92c0d5ab032a
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: minecraft-datadir
          mountPath: /data
  volumes:
    - name: minecraft-datadir
      persistentVolumeClaim:
        claimName: minecraft-datadir
