---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-mirror-config
  namespace: gitea-mirror
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  # storageClassName: <storage-class>   # uncomment to override the default
