---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-netobserv-operator-namespace.yaml
  - netobserv-operator-operatorgroup.yaml
  - netobserv-operator-subscription.yaml
namespace: openshift-netobserv-operator
