apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-ipvlan-l3
resources:
  - multus-ipvlan-l3-namespace.yaml
  - ipvlan-l3-networkattachmentdefinition.yaml
  - multus-ipvlan-l3-test-pod.yaml
