apiVersion: v1
kind: Pod
metadata:
  name: multus-ipvlan-l3-test
  namespace: multus-ipvlan-l3
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-l3
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tools
      image: registry.redhat.io/openshift4/ose-tools-rhel9:latest
      command: ["sleep", "infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
