---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-pg
  namespace: forgejo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  instances: 1
  enablePDB: false
  imagePullPolicy: IfNotPresent
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
  storage:
    size: 10Gi
    storageClass: freenas-nvmeof-ssd-csi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
