---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-keycloak
  namespace: forgejo
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-openshift
  target:
    name: forgejo-keycloak
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        key: forgejo
        secret: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: forgejo-keycloak
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
