apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhods-operator
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  name: rhods-operator
  channel: fast-3.2
  source: redhat-operators
  sourceNamespace: openshift-marketplace
