---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-chains
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  labels:
    operator.tekton.dev/operand-name: tektonchains
    pod-security.kubernetes.io/enforce: privileged
