apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: qbittorrent
  labels:
    app.kubernetes.io/name: prowlarr
    app.kubernetes.io/part-of: qbittorrent-vpn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: qbittorrent
  ports:
    - name: http
      port: 9696
      targetPort: prowlarr-http
      protocol: TCP
