apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/lvms-operator
  - lvmcluster-lvmcluster.yaml
  - lvms-lvm-local-storage-immediate-storageclass.yaml
