apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: guest-dmz
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  ipAddressPools:
    - guest-dmz
  aggregationLength: 32
  communities:
    - guest-dmz
