apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: iot
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: '0'
spec:
  addresses:
    - 10.10.151.0/24
  autoAssign: false
  avoidBuggyIPs: true
