apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mikrotik-bgppeer.yaml
  - tier-community.yaml
  - trusted-lan-ipaddresspool.yaml
  - trusted-lan-bgpadvertisement.yaml
  - iot-ipaddresspool.yaml
  - iot-bgpadvertisement.yaml
  - guest-dmz-ipaddresspool.yaml
  - guest-dmz-bgpadvertisement.yaml
