apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: trusted-lan
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: '0'
spec:
  addresses:
    - 10.10.150.0/24
  autoAssign: false
