---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: virtualmachine-ops-token
  namespace: service-accounts
spec:
  refreshInterval: "0"
  secretStoreRefs:
    - name: onepassword-sdk-claude
      kind: ClusterSecretStore
  selector:
    secret:
      name: virtualmachine-ops-token
  data:
    - conversionStrategy: None
      match:
        secretKey: token
        remoteRef:
          remoteKey: ocp-virtualmachine-ops
          property: token
