---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-node-cleanup
  namespace: openshift-cluster-api
rules:
- apiGroups: ["cluster.x-k8s.io"]
  resources: ["machines"]
  verbs: ["get", "list", "patch"]
