---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: casval-bmc-secret
  namespace: openshift-cluster-api
spec:
  target:
    name: casval-bmc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  secretStoreRef:
    name: onepassword-sdk-ocp-pull
    kind: ClusterSecretStore
  refreshInterval: 1h
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: casval_bmc
        metadataPolicy: None
        nullBytePolicy: Ignore