apiVersion: v1
kind: Pod
metadata:
  name: multus-pod-nad-test
  namespace: multus-pod-nad
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan45-trunk
spec:
  containers:
    - name: tools
      image: registry.redhat.io/openshift4/ose-tools-rhel9:latest
      command: ["sleep", "infinity"]
