apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/david-igou/gitops-catalog/ansible-automation-platform/operator/overlays/stable-2.5?ref=add-aap-2.5
- automationcontroller.yaml
- automationhub-admin-password-externalsecret.yaml
- automationhub-console-link.yaml
- automationhub.yaml
- controller-admin-password-externalsecret.yaml
- controller-console-link.yaml
- eda-admin-password-externalsecret.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
