---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firecrawl-nuq-postgres
  namespace: firecrawl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: freenas-nvmeof-ssd-csi
  resources:
    requests:
      storage: 10Gi
