apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llmkube-system
resources:
  - llmkube-system-namespace.yaml
helmCharts:
- name: llmkube
  namespace: llmkube-system
  version: 0.7.5
  releaseName: llmkube
  repo: https://defilantech.github.io/LLMKube
  valuesInline: {}
