---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: '10'
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh.apps.ocp.igou.systems
    backend:
      baseUrl: https://rhdh.apps.ocp.igou.systems
      cors:
        origin: https://rhdh.apps.ocp.igou.systems
      auth:
        externalAccess:
          - type: legacy
            options:
              subject: legacy-default-config
              secret: "${BACKEND_SECRET}"
      database:
        client: pg
        connection:
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
