---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-networkpolicy.yaml
  - allow-observed-networkpolicy.yaml
  - rhdh-namespace.yaml
  - rhdh-operatorgroup.yaml
  - rhdh-subscription.yaml
  - rhdh-postgres-credentials-externalsecret.yaml
  - rhdh-backend-secret-externalsecret.yaml
  - cnpg-s3-credentials-externalsecret.yaml
  - rhdh-pg-objectstore.yaml
  - rhdh-pg-scheduledbackup.yaml
  - rhdh-pg-cluster.yaml
  - app-config-rhdh-configmap.yaml
  - rhdh-developer-hub-backstage.yaml
