---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: rhdh-oauth-proxy-cookie
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: '9'
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
