---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-oauth-proxy-cookie
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-wave: '9'
spec:
  refreshInterval: '0'
  target:
    name: rhdh-oauth-proxy-cookie
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        cookie-secret: '{{ .password }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: rhdh-oauth-proxy-cookie
