---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-backend-secret
  namespace: rhdh
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '9'
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp-pull
  target:
    name: rhdh-backend-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: rhdh-backend-secret
        metadataPolicy: None
        nullBytePolicy: Ignore
