---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitea-nonroot-v2
  namespace: gitea
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-nonroot-v2
subjects:
  - kind: ServiceAccount
    name: gitea
    namespace: gitea
  - kind: ServiceAccount
    name: gitea-valkey-primary
    namespace: gitea
