apiVersion: batch/v1
kind: Job
metadata:
  name: {{.JobName}}-{{.storageClassName}}-{{.Replica}}-{{.Iteration}}
  labels:
    name: pod-job
spec:
  parallelism: 1
  completions: 1
  completionMode: Indexed
  template:
    spec:
      containers:
      - name: hello-world
        image: {{.containerImage}}
        command: ["df"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{.JobName}}-{{.storageClassName}}-pvc-{{.Replica}}-{{.Iteration}}
      restartPolicy: Never