---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab-ssh
  namespace: redhat-lab
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
    verbs:
      - get
  - apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/portforward
      - virtualmachineinstances/portforward
    verbs:
      - get
