---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - logging-loki-s3-externalsecret.yaml
  - logging-loki-lokistack.yaml
  - collector-serviceaccount.yaml
  - collector-collect-application-logs-clusterrolebinding.yaml
  - collector-collect-infrastructure-logs-clusterrolebinding.yaml
  - collector-collect-audit-logs-clusterrolebinding.yaml
  - collector-logging-collector-logs-writer-clusterrolebinding.yaml
  - collector-clusterlogforwarder.yaml
  - central-logging-alertingrule.yaml
