---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - logging-loki-s3-externalsecret.yaml
  - logging-loki-lokistack.yaml
  - collector-serviceaccount.yaml
  - collector-rbac.yaml
  - collector-clusterlogforwarder.yaml
  - central-logging-alertingrule.yaml
