apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-vlan
resources:
  - multus-vlan-namespace.yaml
  - vlan80-networkattachmentdefinition.yaml
  - multus-vlan-test-pod.yaml
