apiVersion: v1
kind: Pod
metadata:
  name: multus-vlan-test
  namespace: multus-vlan
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
      [
        {
          "name": "vlan80",
          "default-route": ["10.10.80.1"]
        }
      ]
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: tools
      image: registry.redhat.io/openshift4/ose-tools-rhel9:latest
      command: ["sleep", "infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
