apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: config-bundle-secret
  namespace: quay-enterprise
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp
  target:
    name: config-bundle-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        config.yaml: |-
          DISTRIBUTED_STORAGE_CONFIG:
            s3Storage:
              - RHOCSStorage
              - hostname: truenas.igou.systems
                port: "30000"
                access_key: {{ .quay_user_access_key }}
                secret_key: {{ .quay_user_secret_key }}
                is_secure: true
                bucket_name: quay
                storage_path: /datastorage/registry
          DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
          DISTRIBUTED_STORAGE_PREFERENCE:
              - s3Storage
          SUPER_USERS:
            - igou
          FEATURE_USER_CREATION: false
  dataFrom:
  - extract:
      key: minio-user-secret-keys
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None