---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-aap
  namespace: homepage
spec:
  refreshInterval: 24h
  data:
    - secretKey: HOMEPAGE_VAR_AAP_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homepage-aap
        property: aap_token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-openshift
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
