{{- range $tenant := .Values.tenants }}
{{- $ns := include "pac-tenant.namespace" (dict "root" $ "tenant" $tenant) }}
{{- if $tenant.secrets }}

{{- range $secret := ($tenant.secrets.imagePullSecrets | default list) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name | quote }}
  namespace: {{ $ns | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    {{- include "pac-tenant.labels" (dict "tenant" $tenant) | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.clusterSecretStore | quote }}
  target:
    name: {{ $secret.name | quote }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson }}` }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ $secret.onepasswordItem | quote }}
        property: dockerconfigjson
{{- end }}

{{- range $secret := ($tenant.secrets.workspaceSecrets | default list) }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name | quote }}
  namespace: {{ $ns | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    {{- include "pac-tenant.labels" (dict "tenant" $tenant) | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.clusterSecretStore | quote }}
  target:
    name: {{ $secret.name | quote }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $secret.onepasswordItem | quote }}
{{- end }}

{{- end }}
{{- end }}
