apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-networkpolicy.yaml
  - allow-observed-networkpolicy.yaml
  - ../../../components/ansible-automation-platform
  - aap-admin-password-externalsecret.yml
  - aap-ansibleautomationplatform.yml
