---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: molecule-kubernetes
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - edit
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - edit
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
