---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-read-only-token
  namespace: service-accounts
  annotations:
    kubernetes.io/service-account.name: cluster-read-only
type: kubernetes.io/service-account-token
