---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-accounts-namespace.yaml
  - cluster-read-only-serviceaccount.yaml
  - cluster-read-only-token-secret.yaml
  - cluster-read-only-clusterrolebinding.yaml
  - cluster-edit-serviceaccount.yaml
  - cluster-edit-token-secret.yaml
  - claude-edit-serviceaccount.yaml
  - claude-edit-token-secret.yaml
  - ansible-molecule-serviceaccount.yaml
  - ansible-molecule-token-secret.yaml
  - ansible-molecule-clusterrole.yaml

helmGlobals:
  chartHome: ../../.helm/charts

helmCharts:
  - name: namespace-rolebindings
    releaseName: cluster-edit
    valuesFile: values.yaml
