bindings:
  - serviceAccount:
      name: cluster-edit
      namespace: service-accounts
    clusterRole: edit
    namespaces:
      - default
  - serviceAccount:
      name: claude-edit
      namespace: service-accounts
    clusterRole: edit
    namespaces:
      - claude
  - serviceAccount:
      name: ansible-molecule
      namespace: service-accounts
    clusterRole: molecule-kubernetes
    namespaces:
      - molecule
