{
 "title": "cert-manager",
 "description": "Monitors Certificates managed by cert-manager",
 "tags": [ "cert-manager" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds, exported_namespace)"
    }
   },
   {
    "name": "certificate",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Certificates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time Left",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time()) by (name,exported_namespace) )",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status) by (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time()) BY (name,exported_namespace)",
     "legendFormat": "{{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "ACME Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall requests per 2m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status, path)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  }
 ]
}