{
 "title": "Forgejo",
 "tags": [
  "forgejo",
  "apps"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gitea_users{job=\"forgejo-http\"}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "gitea_repositories{job=\"forgejo-http\"}"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "gitea_issues{job=\"forgejo-http\"}"
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gitea_organizations{job=\"forgejo-http\"}"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "gitea_stars{job=\"forgejo-http\"}"
    }
   ]
  },
  {
   "title": "Resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"forgejo-http\"}",
     "legendFormat": "forgejo"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"forgejo-http\"}",
     "legendFormat": "forgejo"
    }
   ]
  }
 ]
}