apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-clone-read
spec:
  to:
    kind: Service
    name: el-clone-read
  port:
    targetPort: http-listener
  tls:
    termination: edge

