---
apiVersion: v1
kind: Pod
metadata:
  name: trunk-test
  namespace: multus-trunk-casval
  annotations:
    k8s.v1.cni.cncf.io/networks: |-
      [
        {
          "name": "vlan45-trunk",
          "ips": ["10.10.45.226/24"],
          "interface": "vlan45"
        }
      ]
spec:
  nodeSelector:
    kubernetes.io/hostname: casval
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: Never
  containers:
    - name: net
      image: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:1d7c5517a4a1a8e2688620b39ee980e82505ca1ab7ae5541b5463120ae9b3897
      command: ["sleep", "infinity"]
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
