{{- if and .Values.auth.enabled .Values.auth.externalSecret -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.auth.externalSecret.name }}
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: {{ .Values.auth.externalSecret.name }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.auth.externalSecret.onePasswordSecretName }}
{{ end }}
