apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: n8n-nonroot-v2
  namespace: n8n
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-scc-nonroot-v2
subjects:
- kind: ServiceAccount
  name: n8n
  namespace: n8n
