apiVersion: external-secrets.io/v
kind: ExternalSecret
metadata:
  name: n8n-secrets
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: n8n-secrets
      metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp
  target:
    creationPolicy: Owner
    deletionPolicy: Retain