apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-scc-nonroot-v2
  namespace: n8n
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot-v2
  resources:
  - securitycontextconstraints
  verbs:
  - use
