---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mx3d
resources:
  - mx3d-namespace.yaml
  - mx3d-windows-exporter.yaml
  - mx3d-ohmgraphite.yaml
  - mx3d-prometheusrule.yaml
