---
apiVersion: v1
kind: Endpoints
metadata:
  # Must match the Service name for endpoint discovery.
  name: mx3d-ohmgraphite
  labels:
    app.kubernetes.io/name: mx3d-ohmgraphite
    app.kubernetes.io/part-of: mx3d
subsets:
  - addresses:
      - ip: 10.10.10.23
    ports:
      - name: metrics
        port: 4445
        protocol: TCP
