---
tenants:
  - name: simple-tenant
    url: https://forgejo.apps.ocp.igou.systems/igou-io/simple-tenant

  - name: secrets-tenant
    url: https://forgejo.apps.ocp.igou.systems/igou-io/secrets-tenant
    secrets:
      imagePullSecrets:
        - name: ghcr-readonly
          onepasswordItem: ci-ghcr-readonly
      workspaceSecrets:
        - name: snyk-org-token
          onepasswordItem: ci-snyk-org

  - name: heavy-tenant
    url: https://forgejo.apps.ocp.igou.systems/igou-io/heavy-tenant
    quota:
      requests.cpu: "16"
      requests.memory: 32Gi
      limits.cpu: "32"
      limits.memory: 64Gi
    concurrencyLimit: 1

  - name: custom-1p-tenant
    url: https://forgejo.apps.ocp.igou.systems/igou-io/custom-1p-tenant
    onepasswordItem: legacy-named-forgejo-item

  - name: container-builder
    url: https://forgejo.apps.ocp.igou.systems/igou-io/container-builder
    imageStreams:
      - name: ee-minimal-rhel9
        from: registry.redhat.io/ansible-automation-platform-26/ee-minimal-rhel9:latest
    secrets:
      serviceAccountSecrets:
        - name: quay-push-config
          onepasswordItem: ci-quay-container-builder
          asImagePullSecret: true
