---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - clusterroles.yaml
  - clusterrolebindings.yaml
  - externalsecrets.yaml
  - identities-pvc.yaml
  - auth-login-deployment.yaml
