apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-nvmeof-fast-config
  namespace: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-ocp-pull
  target:
    name: democratic-csi-nvmeof-fast-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |-
          driver: freenas-nvmeof
          instance_id:
          node:
            mount:
              # predominantly used to facilitate testing
              # mount_flags should generally be defined in storage classes, etc
              mount_flags: ""
              # should fsck be executed before mounting the fs
              checkFilesystem:
                xfs:
                  enabled: true
                  customOptions: []
                ext4:
                  enabled: true
                  customOptions: []
                  customFilesystemOptions: []
                btrfs:
                  enabled: true
                  customOptions: []
                  customFilesystemOptions: []
          httpConnection:
            protocol: https
            host: {{ .truenas_host }}
            port: 443
            apiKey: {{ .truenas_api_key }}
            allowInsecure: false
            apiVersion: 2
          sshConnection:
            host: {{ .truenas_host }}
            port: 22
            username: {{ .truenas_user }}
            privateKey: |-{{ .truenas_ssh_key | b64dec | nindent 4}}
          zfs:
            cli:
              sudoEnabled: true
              paths:
                zfs: /sbin/zfs
                zpool: /sbin/zpool
                sudo: /bin/sudo
                chroot: /sbin/chroot
            datasetParentName: fast/k8s/vols
            detachedSnapshotsDatasetParentName: fast/k8sbak/vols
            zvolCompression:
            zvolDedup:
            zvolEnableReservation: false
            zvolBlocksize:
          nvmeof:
            transports:
              - "tcp://{{ .truenas_host }}:4420"
            namePrefix: "csi-"
            nameSuffix: "-sno"
            ports:
              - 1

            # http://<ip>/api/docs/current/api_methods_nvmet.subsys.create.html
            subsystemTemplate:
              pi_enable: true
              qid_max:
              ieee_oui:
              ana:

            # http://<ip>/api/docs/current/api_methods_nvmet.namespace.create.html
            # currently none of the fields can be tweaked so leave empty for now
            namespaceTemplate:
  dataFrom:
  - extract:
      key: truenas
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
