---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: freenas-nvmeof-fast-csi
spec:
  claimPropertySets:
    - accessModes: [ReadWriteOnce]
      volumeMode: Block
  cloneStrategy: snapshot
