apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
spec:
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  ingress_type: Route
  no_log: true
  redis_mode: standalone
  image_pull_policy: Always
  hostname: gateway-test.apps.sno.igou.systems
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
    database_secret: external-postgres-configuration-gateway
  route_host: gateway-test.apps.sno.igou.systems
  hub:
    file_storage_storage_class: freenas-nfs-ssd-csi
    redis_storage_class: freenas-iscsi-ssd-csi
    postgres_configuration_secret: external-postgres-configuration-hub
  controller:
    postgres_configuration_secret: external-postgres-configuration-controller
  eda:
    database:
        database_secret: external-postgres-configuration-eda
