kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: aap-postgres
spec:
  managed:
    roles:
      - name: aap
        ensure: present
        login: true
      - name: gateway
        ensure: present
        login: true
        passwordSecret:
          name: external-postgres-configuration-gateway
      - name: hub
        ensure: present
        login: true
        passwordSecret:
          name: external-postgres-configuration-hub
      - name: controller
        ensure: present
        login: true
        passwordSecret:
          name: external-postgres-configuration-controller
      - name: eda
        ensure: present
        passwordSecret:
          name: external-postgres-configuration-eda
        login: true
  instances: 5
  switchoverDelay: 5
  replicationSlots:
    highAvailability:
      enabled: true
  logLevel: info
  primaryUpdateStrategy: unsupervised
  postgresql:
    synchronous:
      method: any
      number: 3
      dataDurability: preferred
  storage:
    size: 20Gi
  walStorage:
    size: 20Gi

