---
apiVersion: v1
kind: Secret
metadata:
  name: external-postgres-configuration-hub
stringData:
  host: "aap-postgres-rw.aap-external-db-cnpg.svc.cluster.local"
  port: "5432"
  database: "hub"
  username: "hub"
  password: "hub" # This is a bad idea
  type: "unmanaged"
type: Opaque
