apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-ipvlan-l2
resources:
  - multus-ipvlan-l2-namespace.yaml
  - ipvlan-l2-networkattachmentdefinition.yaml
  - multus-ipvlan-l2-test-pod.yaml
