apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - ntfy-namespace.yaml
  - ntfy-config-pvc.yaml
  # Uncomment once the probe is populated via /add-probe https://ntfy.apps.ocp.igou.systems
  # - ntfy-probe.yaml
configMapGenerator:
  - name: ntfy-server-config
    files:
      - server.yml
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
- name: app-template
  namespace: ntfy
  version: 4.6.2
  releaseName: ntfy
  repo: oci://ghcr.io/bjw-s-labs/helm
  valuesFile: values-dummy.yaml
  valuesInline:
    controllers:
      ntfy:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        pod:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
        containers:
          app:
            args: ["serve"]
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.24.0@sha256:f8a9b104313b87cc24ae4f775f39e6328205b57dff6ede3eaf098a91e5d79f59
              pullPolicy: IfNotPresent
            env: {}
            probes:
              liveness:
                enabled: true
                type: TCP
              readiness:
                enabled: true
                type: TCP
              startup:
                enabled: true
                type: TCP
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop:
                  - ALL
    persistence:
      cache:
        type: persistentVolumeClaim
        existingClaim: ntfy-config
        advancedMounts:
          ntfy:
            app:
              - path: /var/cache/ntfy
      config:
        type: configMap
        name: ntfy-server-config
        globalMounts:
          - path: /etc/ntfy/server.yml
            subPath: server.yml
            readOnly: true
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: 80
            targetPort: 8080
    ingress:
      app:
        className: openshift-default
        annotations:
          route.openshift.io/termination: edge
        hosts:
          - host: ntfy.apps.ocp.igou.systems
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    serviceAccount:
      ntfy:
        enabled: true
    serviceMonitor:
      app:
        serviceName: ntfy-app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 60s
            scrapeTimeout: 10s
