---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: upsmonitor
resources:
  - upsmonitor-namespace.yaml
  - upsmonitor-node-exporter-service.yaml
  - upsmonitor-node-exporter-endpoints.yaml
  - upsmonitor-node-exporter-servicemonitor.yaml
  - upsmonitor-nut-exporter-service.yaml
  - upsmonitor-nut-exporter-endpoints.yaml
  - upsmonitor-nut-exporter-servicemonitor.yaml
  - upsmonitor-prometheusrule.yaml
