apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-macvlan-dhcp-nginx
resources:
  - namespace.yaml
  - nad-vlan45.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
