apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudnative-pg-operatorgroup.yaml
- cloudnative-pg-servicemonitor.yaml
- cloudnative-pg-subscription.yaml
- cnpg-metrics-service.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
