apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: casval-bmc-secret
  namespace: casval
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-sdk-hub-pull
  target:
    name: casval-bmc-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: casval_bmc
