apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: democratic-csi
resources:
  - ../../../components/democratic-csi
  - democratic-csi-iscsi-fast-config-externalsecret.yaml
  - democratic-csi-iscsi-ssd-config-externalsecret.yaml
  - democratic-csi-iscsi-cold-config-externalsecret.yaml
  - democratic-csi-nfs-fast-config-externalsecret.yaml
  - democratic-csi-nfs-ssd-config-externalsecret.yaml
  - democratic-csi-nfs-cold-config-externalsecret.yaml
  - democratic-csi-nvmeof-fast-config-externalsecret.yaml
  - democratic-csi-nvmeof-ssd-config-externalsecret.yaml
  - democratic-csi-nvmeof-cold-config-externalsecret.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
