apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - quay-local-pull-externalsecret.yaml
  - omnigent-namespace.yaml
  - omnigent-sandboxes-namespace.yaml
  - omnigent-pg-cluster.yaml
  - omnigent-pg-backup-objectstore.yaml
  - omnigent-pg-daily-scheduledbackup.yaml
  - cnpg-s3-credentials-externalsecret.yaml
  - omnigent-auth-externalsecret.yaml
  - omnigent-machine-client-externalsecret.yaml
  - omnigent-opencode-go-externalsecret.yaml
  - omnigent-openshell-client-externalsecret.yaml
  - omnigent-creds-externalsecret.yaml
  - omnigent-config-configmap.yaml
  - omnigent-sandbox-config-configmap.yaml
  - omnigent-openshell-gateway-configmap.yaml
  - omnigent-test-agent-configmap.yaml
  - omnigent-server-serviceaccount.yaml
  - omnigent-runner-serviceaccount.yaml
  - omnigent-sandbox-manager-role.yaml
  - omnigent-sandbox-manager-rolebinding.yaml
  - omnigent-runner-nonroot-role.yaml
  - omnigent-runner-nonroot-rolebinding.yaml
  - omnigent-artifacts-pvc.yaml
  - omnigent-deployment.yaml
  - omnigent-service.yaml
  - omnigent-route.yaml
