apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 1password-use-anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: 1password-connect
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid