namespace: external-secrets-operator
resources:
  - 1password-connect-cluster-role-binding.yaml
helmCharts:
- name: connect
  includeCRDs: true
  valuesInline:
    connect:
      applicationName: onepassword-connect
      api:
        name: connect-api
        imageRepository: 1password/connect-api
        resources: {}
        httpPort: 8080
        httpsPort: 8443
      sync:
        name: connect-sync
        imageRepository: 1password/connect-sync
        resources: {}
        httpPort: 8081
      serviceType: NodePort
      credentialsName: 1p-credentials
      credentialsKey: 1password-credentials.json
      tls:
        enabled: false
        secret: op-connect-tls
      dataVolume:
        name: shared-data
        type: emptyDir
        values: {}
      imagePullPolicy: IfNotPresent
      version: "{{ .Chart.AppVersion }}"
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      probes:
        liveness: true
        readiness: true
      annotations: {}
      labels: {}
      podAnnotations: {}
      podLabels: {}
      tolerations:
        - operator: Exists
  releaseName: connect
  version: 2.0.5
  repo: https://1password.github.io/connect-helm-charts