---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: external-secrets
  namespace: external-secrets-operator
  labels:
    app.kubernetes.io/part-of: external-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
