apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openshell-credential-encryption-key
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '-3'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-lab-agents
  target:
    name: openshell-credential-encryption-key
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: openshell
