---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    kubernetes.io/service-account.name: grafana
type: kubernetes.io/service-account-token
