---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-oauth-cookie
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
