---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-cookie
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  refreshInterval: '0'
  target:
    name: grafana-oauth-cookie
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        cookie-secret: '{{ .password }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-oauth-cookie
