---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-namespace.yaml
  - grafana-operatorgroup.yaml
  - grafana-subscription.yaml
  - grafana-serviceaccount.yaml
  - grafana-rbac.yaml
  - grafana-sa-token-secret.yaml
  - grafana-oauth-cookie-password.yaml
  - grafana-oauth-cookie-externalsecret.yaml
  - grafana-grafana.yaml
  - grafana-thanos-datasource.yaml
  - grafana-dashboard-7587.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
