{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '1'
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
      {{- with .Values.externalSecrets.vaults }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets-operator
{{ end }}
