apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ocs-storagecluster.yml
- odf-operator-subscription.yml
- quay-bucket-backingstore.yml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
