apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: "stable-4.15"
  installPlanApproval: Automatic