---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-config
  namespace: metube
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: freenas-nvmeof-ssd-csi
