---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent-sandbox-system-namespace.yaml
  - agent-sandbox-operator-operatorgroup.yaml
  - agent-sandbox-operator-subscription.yaml
namespace: agent-sandbox-system
