apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/onepassword-connect
  - onepassword-connect-nonroot-v2-rolebinding.yaml
  - connect-allow-eso-and-router-networkpolicy.yaml
  - onepassword-connect-route.yaml
