apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytorch
  template:
    metadata:
      labels:
        app: pytorch
    spec:
      containers:
      - name: pytorch
        image: igou-registry-quay-quay-enterprise.apps.sno.igou.systems/gfx803/rocm6_gfx803_pytorch:latest
        resources:
          limits:
            amd.com/gpu: 1
          requests:
            amd.com/gpu: 1
        tty: true
      imagePullSecrets:
      - name: igou-quay-gfx803-robotaccount
      restartPolicy: Always