apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hermes-nested-test
resources:
  - hermes-nested-test-namespace.yaml
  - hermes-nested-podman-securitycontextconstraints.yaml
  - system-openshift-scc-hermes-nested-podman-clusterrole.yaml
  - system-openshift-scc-hermes-nested-podman-rolebinding.yaml
  - hermes-agent-test-serviceaccount.yaml
  - hermes-agent-test-config-configmap.yaml
  - hermes-agent-test-data-pvc.yaml
  - hermes-agent-test-deployment.yaml
