apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: hermes-agent-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hermes-agent
    app.kubernetes.io/part-of: hermes-agent
    app.kubernetes.io/version: 0.8.0
    helm.sh/chart: hermes-agent-0.1.0
  name: hermes-agent-test
