apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  secretStoreRef:
    name: onepassword-sdk-ocp
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: tailscale-oauth