apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  secretStoreRef:
    name: 1password
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      key: tailscale-oauth