---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-sandboxed-containers-operator-namespace.yaml
  - sandboxed-containers-operator-operatorgroup.yaml
  - sandboxed-containers-operator-subscription.yaml
  - kataconfig.yaml
namespace: openshift-sandboxed-containers-operator
