apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/external-secrets-operator
  - onepassword-ocp-pull-clustersecretstore.yaml
  - onepassword-ocp-push-clustersecretstore.yaml
  - onepassword-claude-clustersecretstore.yaml
  - onepassword-lab-openshift-clustersecretstore.yaml
  - onepassword-lab-redhat-clustersecretstore.yaml
  - onepassword-lab-container-registries-clustersecretstore.yaml
  - onepassword-lab-forgejo-clustersecretstore.yaml
  - onepassword-lab-github-clustersecretstore.yaml
  - onepassword-lab-s3-clustersecretstore.yaml
  - onepassword-lab-routeros-clustersecretstore.yaml
  - onepassword-lab-external-api-keys-clustersecretstore.yaml
  - onepassword-lab-aap-clustersecretstore.yaml
  - onepassword-lab-serviceaccounts-clustersecretstore.yaml
