apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-sdk-ocp-pull
spec:
  refreshInterval: 3600
  retrySettings:
    retryInterval: 1h0m0s
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword-connect.svc:8080
      vaults:
        ocp-pull: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets-operator
