apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-macvlan-whereabouts-nginx
resources:
  - multus-macvlan-whereabouts-nginx-namespace.yaml
  - vlan45-macvlan-whereabouts-networkattachmentdefinition.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - nginx-route.yaml
