apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: aap-admin-password
  namespace: ansible-automation-platform
spec:
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  secretStoreRef:
    name: onepassword-sdk-hub-pull
    kind: ClusterSecretStore
  refreshInterval: "1h"
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: aap-admin-password
      metadataPolicy: None
