apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-admin-password
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: controller-admin-password
      metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Orphan
    deletionPolicy: Retain
    name: aap-admin-password