apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-admin-password
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: controller-admin-password
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: controller-password