apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: controller-admin-password
  namespace: ansible-automation-platform
  spec:
    dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: controller-admin-password
        metadataPolicy: None
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: 1password
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: controller-admin-password