apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/redhat-cop/gitops-catalog/ansible-automation-platform/operator/overlays/stable-2.5-cluster-scoped
- aap-ansibleautomationplatform.yml
- aap-console-link.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
