apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-acme
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    email: igou.david@gmail.com
    privateKeySecretRef:
      name: acme-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: credential
              name: dns-token
            email: igou.david@gmail.com
        selector:
          dnsZones:
            - igou.systems
            - casval.igou.systems
