apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.9.213
    path: /mnt/cold/media/data/media
    readOnly: true
  claimRef:
    namespace: jellyfin
    name: jellyfin-media
