apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-pod-nad-privileged
resources:
  - multus-pod-nad-privileged-namespace.yaml
  - vlan45-trunk-networkattachmentdefinition.yaml
  - privileged-sa-serviceaccount.yaml
  - use-scc-privileged-role.yaml
  - privileged-sa-scc-rolebinding.yaml
  - multus-pod-nad-test-privileged-pod.yaml
