apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multus-pod-nad-privileged
resources:
  - namespace.yaml
  - nad-vlan45.yaml
  - serviceaccount.yaml
  - scc-role.yaml
  - scc-rolebinding.yaml
  - pod.yaml
