apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-scc-privileged
  namespace: multus-pod-nad-privileged
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
