---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vscode
resources:
  - vscode-namespace.yaml
  - vscode-node-exporter-service.yaml
  - vscode-node-exporter-endpoints.yaml
  - vscode-node-exporter-servicemonitor.yaml
  - vscode-alerts-prometheusrule.yaml
