apiVersion: v1
kind: Service
metadata:
  name: minecraft-exporter
  annotations:
    tailscale.com/expose: "true"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
  ports:
    - name: metrics
      port: 9150
      targetPort: metrics
