apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: goodbye
  namespace: test-tekton-pipeline
spec:
  params:
  - name: username
    type: string
  steps:
    - name: goodbye
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Goodbye $(params.username)!"