---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: infra-https
  namespace: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.blackbox-exporter.svc:9115
  targets:
    staticConfig:
      static:
        - https://automation.apps.ocp.igou.systems
        - https://grafana.apps.ocp.igou.systems
        - https://truenas.igou.systems
        - https://home.apps.ocp.igou.systems
        - https://forgejo.apps.ocp.igou.systems
        - https://rhdh.apps.ocp.igou.systems
        - https://openshift-gitops-server-openshift-gitops.apps.ocp.igou.systems
        - https://keycloak.apps.ocp.igou.systems
        - https://console-openshift-console.apps.ocp.igou.systems
        - https://devspaces.apps.ocp.igou.systems
        - https://hermes-dashboard.apps.ocp.igou.systems
        - https://hermes-sre-am-relay.apps.ocp.igou.systems/healthz
        - https://headlamp.rk8s.igou.systems
        - https://prometheus.rk8s.igou.systems
      labels:
        tier: standard
        category: infra
        owner: platform
