---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: saas-https
  namespace: blackbox-exporter
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.blackbox-exporter.svc:9115
  targets:
    staticConfig:
      static: []
      labels:
        tier: standard
        category: saas
