---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-dev-spaces-namespace.yaml
  - openshift-dev-spaces-operatorgroup.yaml
  - openshift-dev-spaces-subscription.yaml
