apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualmachine-deployer
subjects:
- kind: ServiceAccount
  name: virtualmachine-deployer
  namespace: openshift-cnv
roleRef:
  kind: ClusterRole
  name: virtualmachine-deployer
  apiGroup: rbac.authorization.k8s.io