apiVersion: v1
kind: Secret
metadata:
  name: virtualmachine-reader-token
  namespace: openshift-cnv
  annotations:
    kubernetes.io/service-account.name: virtualmachine-reader
type: kubernetes.io/service-account-token