apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualmachine-reader
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances", "virtualmachines"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["list"]