apiVersion: v1
kind: Secret
metadata:
  name: virtualmachine-deployer-token
  namespace: openshift-cnv
  annotations:
    kubernetes.io/service-account.name: virtualmachine-deployer
type: kubernetes.io/service-account-token